name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  update-changelog-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.5.1'

      - name: Update Changelog and Package Version
        run: |
          # Récupérer le dernier tag et enlever le 'v' si présent
          TAG_NAME=$(git describe --tags --abbrev=0 | sed 's/^v//')
          CURRENT_DATE=$(date +'%d-%m-%Y')

          # Mettre à jour CHANGELOG.md
          sed -i "s/## \[Unreleased\]/## [$TAG_NAME] $CURRENT_DATE/" CHANGELOG.md

          # Mettre à jour package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$TAG_NAME\"/" package.json

          # Commit et push
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Update changelog and version for $TAG_NAME" || true
          git push
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install
      - run: yarn build

      - run: npm publish --access public