name: run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: npm install -g firebase-tools
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
      - run: yarn install
      - run: firebase emulators:exec --only firestore "yarn test & yarn test-mock"
      - name: Build and publish
        if: github.ref == 'refs/heads/main'
        run: |
          yarn build
          yarn publish